import fs from 'fs';
let code = fs.readFileSync('src/components/ControleRefugo.tsx', 'utf8');

const oldItemUi = `                    {item.status === 'found' ? (\n                      <div className="flex flex-col items-end">\n                        <span className="bg-emerald-100 text-emerald-800 px-2.5 py-1 rounded text-xs font-bold border border-emerald-200">\n                          Rota: {item.rota}\n                        </span>\n                        {item.foundBy && (\n                          <span className="text-[10px] text-gray-500 mt-0.5 font-medium">\n                            Encontrado por: <strong className="text-gray-700">{item.foundBy}</strong>\n                          </span>\n                        )}\n                      </div>\n                    ) : (\n                      <span className="bg-red-100 text-red-800 px-2.5 py-1 rounded text-xs font-bold border border-red-200">\n                        SEM ROTA\n                      </span>\n                    )}\n                    <button\n                      onClick={() => removeScan(item.id)}\n                      className="ml-3 text-gray-400 hover:text-red-500 transition-colors p-1.5 rounded-lg hover:bg-red-50 border border-transparent hover:border-red-200"\n                      title="Remover pacote"\n                    >\n                      <Trash2 className="w-4 h-4" />\n                    </button>`;

const newItemUi = `                    <div className="flex items-center gap-2">\n                      {item.status === 'found' ? (\n                        <div className="flex flex-col items-end">\n                          <span className="bg-emerald-100 text-emerald-800 px-2.5 py-1 rounded text-xs font-bold border border-emerald-200">\n                            Rota: {item.rota}\n                          </span>\n                          {item.foundBy && (\n                            <span className="text-[10px] text-gray-500 mt-0.5 font-medium">\n                              Encontrado por: <strong className="text-gray-700">{item.foundBy}</strong>\n                            </span>\n                          )}\n                        </div>\n                      ) : (\n                        <span className="bg-red-100 text-red-800 px-2.5 py-1 rounded text-xs font-bold border border-red-200">\n                          SEM ROTA\n                        </span>\n                      )}\n                      <button\n                        onClick={() => removeScan(item.id)}\n                        className="ml-1 text-gray-400 hover:text-red-500 transition-colors p-1.5 rounded-lg hover:bg-red-50 border border-transparent hover:border-red-200"\n                        title="Remover pacote"\n                      >\n                        <Trash2 className="w-4 h-4" />\n                      </button>\n                    </div>`;

code = code.replace(oldItemUi, newItemUi);
fs.writeFileSync('src/components/ControleRefugo.tsx', code);
