import React, { useEffect, useMemo, useRef, useState } from 'react';
import Papa from 'papaparse';
import { CalendarDays, Check, Clock3, FileUp, PackageX, TrendingUp, Trash2, Upload, Users } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { getLocalValue, setLocalValue } from '../lib/localPersistence';

type DamageCase = { id: string; solver: string; createdAt: string; resolution: string; damageType: string; category: string; value: number; minutes: number };
type StoredData = { cases: DamageCase[]; updatedAt: string };
const STORAGE_KEY = 'avarias-daily-history-v1';
const colors = ['#35b8df', '#7c9ff3', '#a78bfa', '#53c99a', '#f4af4d', '#fa7080'];
const clean = (v: unknown) => String(v ?? '').replace(/Ã§/g, 'ç').replace(/Ã£/g, 'ã').replace(/Ã¡/g, 'á').replace(/Ã©/g, 'é').replace(/Ã­/g, 'í').replace(/Ã³/g, 'ó').replace(/Ãº/g, 'ú').trim();
const field = (row: Record<string, unknown>, ...names: string[]) => { const key = Object.keys(row).find(k => names.some(n => clean(k).toLowerCase() === n.toLowerCase())); return key ? clean(row[key]) : ''; };
const value = (v: string) => Number(v.replace(/[^0-9,.-]/g, '').replace(/\./g, '').replace(',', '.')) || 0;
const date = (v: string) => { const m = v.match(/(\d{1,2})\/(\w{3})/i); const months: Record<string,number> = {jan:0,fev:1,mar:2,abr:3,mai:4,jun:5,jul:6,ago:7,set:8,out:9,nov:10,dez:11}; const n = new Date(); return m ? new Date(n.getFullYear(), months[m[2].toLowerCase()] ?? n.getMonth(), Number(m[1]), 12).toISOString() : n.toISOString(); };
const aggregate = (items: DamageCase[], prop: keyof DamageCase) => Object.entries(items.reduce<Record<string,number>>((a, x) => { const k = String(x[prop] || 'Não informado'); a[k] = (a[k] || 0) + 1; return a; }, {})).map(([name,total]) => ({name,total})).sort((a,b) => b.total-a.total).slice(0,6);
const money = (n: number) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n);

export function AvariasDashboard() {
  const [data, setData] = useState<StoredData>({cases: [], updatedAt: ''}); const [loaded, setLoaded] = useState(false); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { getLocalValue<StoredData>(STORAGE_KEY).then(x => { if (x) setData(x); setLoaded(true); }); }, []);
  const today = new Date().toISOString().slice(0,10);
  const daily = useMemo(() => data.cases.filter(x => x.createdAt.slice(0,10) === today), [data.cases,today]);
  const stats = useMemo(() => { const times=daily.filter(x=>x.minutes>0).map(x=>x.minutes); return {total:daily.length, value:daily.reduce((a,x)=>a+x.value,0), destruction:daily.filter(x=>x.resolution.toLowerCase().includes('destrui')).length, closed:daily.filter(x=>/encerr|fechad|resolvido/i.test(x.resolution)).length, avg:times.length?times.reduce((a,b)=>a+b,0)/times.length:0}; },[daily]);
  const rankings = useMemo(() => { const now=Date.now(); return {daily:aggregate(daily,'solver'), weekly:aggregate(data.cases.filter(x=>now-new Date(x.createdAt).getTime()<6048e5),'solver'), monthly:aggregate(data.cases.filter(x=>now-new Date(x.createdAt).getTime()<26784e5),'solver')}; },[data.cases,daily]);
  const importCsv = (file: File) => Papa.parse<Record<string,unknown>>(file,{header:true,skipEmptyLines:true,complete: async r => { const parsed=r.data.map((row):DamageCase|null=>{const id=field(row,'ID'); const solver=field(row,'Problem Solver'); if(!id||!solver)return null; return {id,solver,createdAt:date(field(row,'Data de criação')),resolution:field(row,'Status de resolução','Resolução'),damageType:field(row,'Tipo de dano'),category:field(row,'Categoria'),value:value(field(row,'VALOR')),minutes:Number(field(row,'Tempo de resolução em minutos'))||0};}).filter((x):x is DamageCase=>!!x); const unique=new Map(data.cases.map(x=>[x.id,x])); parsed.forEach(x=>unique.set(x.id,x)); const next={cases:[...unique.values()],updatedAt:new Date().toISOString()}; setData(next); await setLocalValue(STORAGE_KEY,next);}});
  const chart=(title:string, points:{name:string;total:number}[]) => <section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><h2 className="mb-4 text-base font-black">{title}</h2><div className="h-56">{points.length?<ResponsiveContainer><BarChart data={points} layout="vertical" margin={{left:8,right:18}}><CartesianGrid horizontal={false} stroke="#e5e7eb"/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={120} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="total" radius={[0,6,6,0]}>{points.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Bar></BarChart></ResponsiveContainer>:<div className="flex h-full items-center justify-center text-sm text-slate-400">Importe o CSV diário para visualizar.</div>}</div></section>;
  if(!loaded)return <div className="py-16 text-center text-slate-500">Carregando avarias...</div>;
  const cards: Array<[string, string, React.ElementType, string]> = [['Total de avarias',`${stats.total} casos`,PackageX,'bg-blue-50 text-blue-700'],['Valor total identificado',money(stats.value),TrendingUp,'bg-emerald-50 text-emerald-700'],['Para destruição',`${stats.destruction} casos`,Trash2,'bg-red-50 text-red-600'],['Encerrados',`${stats.closed} casos`,Check,'bg-emerald-50 text-emerald-700'],['Tempo médio de resolução',`${stats.avg.toFixed(1).replace('.',',')} min`,Clock3,'bg-orange-50 text-orange-600']];
  return <div className="space-y-5"><input ref={input} type="file" accept=".csv,text/csv" className="hidden" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0])}/><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div className="flex items-center gap-3"><div className="rounded-xl bg-violet-100 p-3 text-violet-700"><PackageX/></div><div><h1 className="text-3xl font-black tracking-tight">Reporte Diário — Avarias</h1><p className="text-slate-500">Indicadores essenciais para acompanhamento diário</p></div></div><button onClick={()=>input.current?.click()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#253b80] px-4 py-3 text-sm font-bold text-white hover:bg-[#1d2f69]"><Upload className="h-4 w-4"/>Carregar CSV diário</button></div><p className="flex items-center gap-2 text-xs text-slate-500"><CalendarDays className="h-4 w-4"/>Dados persistidos localmente {data.updatedAt&&`• última importação: ${new Date(data.updatedAt).toLocaleString('pt-BR')}`}</p><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label,val,Icon,style])=><div key={label} className="rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><div className="flex gap-3"><div className={`rounded-xl p-3 ${style}`}><Icon className="h-5 w-5"/></div><div><p className="text-xs font-semibold text-slate-600">{label}</p><p className="mt-1 text-xl font-black">{val}</p></div></div></div>)}</div><div className="grid gap-4 lg:grid-cols-3">{chart('1. Avarias por tipo de dano',aggregate(daily,'damageType'))}{chart('2. Resolução dos casos',aggregate(daily,'resolution'))}{chart('3. Top categorias impactadas',aggregate(daily,'category'))}</div><div className="grid gap-4 lg:grid-cols-3">{chart('4. Ranking diário — Problem Solvers',rankings.daily)}{chart('5. Ranking semanal — Problem Solvers',rankings.weekly)}<section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><h2 className="mb-4 flex items-center gap-2 text-base font-black"><Users className="h-5 w-5 text-violet-600"/>6. Ranking mensal</h2><ol className="space-y-3">{rankings.monthly.length?rankings.monthly.map((x,i)=><li className="flex items-center gap-3" key={x.name}><span className="flex h-7 w-7 items-center justify-center rounded-full bg-violet-100 text-xs font-black text-violet-700">{i+1}</span><span className="flex-1 truncate text-sm font-semibold">{x.name}</span><strong>{x.total}</strong></li>):<li className="py-12 text-center text-sm text-slate-400">Sem histórico mensal.</li>}</ol></section></div><div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm text-slate-600"><FileUp className="mr-2 inline h-4 w-4"/><strong>Importação segura:</strong> o CSV é consolidado pelo ID do caso, evitando duplicidade e preservando o histórico.</div></div>;
}
