import React, { useEffect, useMemo, useRef, useState } from 'react';
import { PackageCheck, Search, Trash2, UploadCloud } from 'lucide-react';
import { getLocalValue, setLocalValue } from '../lib/localPersistence';
import { enrichExpedicao, getChanges, parseBaseDespacho, parseExpedicaoRows, type ExpedicaoStore, type FonteExpedicao } from '../lib/expedicao';

const STORAGE_KEY = 'expedicao-daily-v1';
const empty: ExpedicaoStore = { base: [], aduana: [], auditoria: [], localizados: {}, historico: [], encerramentos: [] };
const color = (state: string) => state === 'A mais' ? 'bg-[#f4c7c3] text-[#b3261e]' : state === 'Faltante' ? 'bg-[#fde9a9] text-[#6d4c00]' : 'bg-emerald-100 text-emerald-800';

export function ExpedicaoPanel() {
  const [store, setStore] = useState<ExpedicaoStore>(empty);
  const [ready, setReady] = useState(false);
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<'todos' | 'A mais' | 'Faltante'>('todos');
  const [selectedDoca, setSelectedDoca] = useState<string | null>(null);
  const [report, setReport] = useState(false);
  const baseInput = useRef<HTMLInputElement>(null);
  const aduanaInput = useRef<HTMLInputElement>(null);
  const auditInput = useRef<HTMLInputElement>(null);

  useEffect(() => { getLocalValue<ExpedicaoStore>(STORAGE_KEY).then(saved => { if (saved) setStore({ ...empty, ...saved, localizados: saved.localizados || {} }); setReady(true); }); }, []);
  const save = async (next: ExpedicaoStore) => { setStore(next); await setLocalValue(STORAGE_KEY, next); };
  const importFile = async (file: File, source: 'base' | FonteExpedicao) => {
    const text = await file.text();
    const next = { ...store, updatedAt: new Date().toISOString(), filenames: { ...store.filenames, [source]: file.name } };
    if (source === 'base') next.base = parseBaseDespacho(text); else {
      const parsed = parseExpedicaoRows(text, source);
      next.historico = [...(store.historico || []), ...getChanges(store[source], parsed, source)].slice(-10000);
      next[source] = parsed;
    }
    await save(next);
  };
  const toggleLocated = (pacote: string) => save({ ...store, localizados: { ...store.localizados, [pacote]: !store.localizados?.[pacote] } });
  const resetExpedicao = async () => {
    if (!window.confirm('Zerar toda a expedição? Base Despacho, Aduana, Auditoria, localizados e histórico atual serão removidos deste navegador.')) return;
    await save(empty);
    setQuery('');
    setFilter('todos');
    setSelectedDoca(null);
    setReport(false);
  };
  const enriched = useMemo(() => enrichExpedicao(store), [store]);
  const rows = enriched.filter(row => (filter === 'todos' || row.classificacao === filter) && (!selectedDoca || row.doca === selectedDoca) && `${row.pacote} ${row.rotaOtimizada} ${row.placa} ${row.onda}`.toLowerCase().includes(query.trim().toLowerCase()));
  const counts = useMemo(() => ({ amais: enriched.filter(row => row.classificacao === 'A mais').length, faltantes: enriched.filter(row => row.classificacao === 'Faltante').length, localizados: enriched.filter(row => store.localizados?.[row.pacote]).length }), [enriched, store.localizados]);
  const heatmap = useMemo(() => Array.from({ length: 20 }, (_, index) => {
    const doca = String(index + 1);
    const records = enriched.filter(row => row.doca === doca);
    return { doca, amais: records.filter(row => row.classificacao === 'A mais').length, faltantes: records.filter(row => row.classificacao === 'Faltante').length };
  }), [enriched]);
  const selectedDockMissing = useMemo(() => selectedDoca ? enriched.filter(row => row.doca === selectedDoca && row.classificacao === 'Faltante') : [], [enriched, selectedDoca]);
  const totalErrors = counts.amais + counts.faltantes;
  const pending = Math.max(0, totalErrors - counts.localizados);
  const recoveryRate = totalErrors ? Math.round((counts.localizados / totalErrors) * 100) : 0;
  const criticalDocks = [...heatmap].sort((a, b) => (b.amais + b.faltantes) - (a.amais + a.faltantes)).slice(0, 3);
  const closeExpedicao = async () => { const closing = { id: `exp-${Date.now()}`, encerradoEm: new Date().toISOString(), ...counts, porDoca: heatmap }; await save({ ...store, encerramentos: [closing, ...(store.encerramentos || [])] }); setReport(true); };
  if (!ready) return <div className="py-16 text-center text-sm text-slate-500">Carregando Expedição…</div>;
  const upload = (label: string, ref: React.RefObject<HTMLInputElement | null>, primary = false) => <button type="button" onClick={() => ref.current?.click()} className={`inline-flex items-center gap-2 rounded-lg px-3.5 py-2.5 text-xs font-black shadow-sm ${primary ? 'bg-[#253b80] text-white hover:bg-[#1f2464]' : 'border border-slate-200 bg-white text-slate-700 hover:bg-slate-50'}`}><UploadCloud className="h-4 w-4" />{label}</button>;
  return <div className="space-y-5">
    <input ref={baseInput} className="hidden" type="file" accept=".csv,text/csv" onChange={e => e.target.files?.[0] && importFile(e.target.files[0], 'base')} />
    <input ref={aduanaInput} className="hidden" type="file" accept=".csv,text/csv" onChange={e => e.target.files?.[0] && importFile(e.target.files[0], 'aduana')} />
    <input ref={auditInput} className="hidden" type="file" accept=".csv,text/csv" onChange={e => e.target.files?.[0] && importFile(e.target.files[0], 'auditoria')} />
    <section className="rounded-2xl border-2 border-blue-200 bg-gradient-to-r from-white via-blue-50 to-white p-5 shadow-md sm:p-6"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><div className="flex items-center gap-2 text-blue-700"><PackageCheck className="h-5 w-5" /><span className="text-xs font-bold uppercase tracking-wider">Expedição — Pacotes AMIS</span></div><h1 className="mt-2 text-3xl font-black tracking-tight text-[#102a67]">Concentração por doca</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">Erros A mais e Faltante consolidados dos CSVs de Aduana e Auditoria.</p></div><div className="flex flex-wrap gap-2">{upload('Atualizar Aduana', aduanaInput, true)}{upload('Atualizar Auditoria', auditInput, true)}<button onClick={resetExpedicao} className="inline-flex items-center gap-2 rounded-lg border-2 border-red-300 bg-white px-3.5 py-2.5 text-xs font-black text-red-700 hover:bg-red-50"><Trash2 className="h-4 w-4"/>Zerar</button><button onClick={closeExpedicao} disabled={!totalErrors} className="rounded-lg border-2 border-amber-400 bg-[#ffd52f] px-3.5 py-2.5 text-xs font-black text-slate-950 disabled:cursor-not-allowed disabled:opacity-50">Encerrar</button></div></div></section>
    {!store.base.length && <section className="flex flex-col justify-between gap-3 rounded-xl border-2 border-amber-400 bg-amber-50 p-4 sm:flex-row sm:items-center"><div><p className="text-sm font-black text-amber-950">Base Despacho ainda não carregada</p><p className="text-xs text-amber-800">Faça esta configuração inicial para localizar doca, rota, onda e placa.</p></div>{upload('Carregar Base Despacho', baseInput)}</section>}
    <section className="rounded-2xl border-2 border-black bg-white p-4 shadow-md"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black text-black">Docas — 20 docas</h2><p className="text-xs text-slate-600">Clique em uma doca para ver os faltantes no painel ao lado.</p></div>{selectedDoca && <button onClick={() => setSelectedDoca(null)} className="rounded-lg border-2 border-black px-3 py-2 text-xs font-black">Limpar seleção</button>}</div><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_330px]"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{heatmap.map(item => { const total = item.amais + item.faltantes; const tone = total === 0 ? 'bg-slate-50 text-slate-500' : total < 4 ? 'bg-yellow-50 text-amber-800' : total < 9 ? 'bg-blue-50 text-blue-800' : 'bg-red-50 text-red-700'; return <button key={item.doca} onClick={() => setSelectedDoca(item.doca)} className={`rounded-xl border-2 border-black p-4 text-left transition hover:-translate-y-0.5 hover:shadow-md ${tone} ${selectedDoca === item.doca ? 'ring-4 ring-blue-300' : ''}`}><div className="text-sm font-black text-black">DOCA {item.doca}</div><div className="mt-4 grid grid-cols-2 gap-2 border-t-2 border-black/20 pt-3 text-xs"><span>A MAIS<b className="mt-1 block text-2xl">{item.amais}</b></span><span>FALTANTES<b className="mt-1 block text-2xl">{item.faltantes}</b></span></div></button>; })}</div><aside className="h-fit max-h-[620px] overflow-y-auto rounded-xl border-2 border-black bg-slate-50 p-4 xl:sticky xl:top-20"><div className="border-b-2 border-black pb-3"><p className="text-xs font-black uppercase text-slate-500">Faltantes da doca</p><h3 className="text-xl font-black text-black">{selectedDoca ? `DOCA ${selectedDoca}` : 'Selecione uma doca'}</h3></div>{selectedDoca ? <div className="mt-3 space-y-2">{selectedDockMissing.length ? selectedDockMissing.map(row => <div key={`${row.origem}-${row.pacote}-${row.rotaInformada}`} className="rounded-lg border-2 border-amber-300 bg-white p-3"><div className="font-mono text-sm font-black text-slate-950">{row.pacote}</div><div className="mt-1 flex justify-between gap-2 text-[10px] font-bold text-slate-500"><span className="capitalize">{row.origem}</span><span>{row.rotaOtimizada || row.rotaInformada || 'Sem rota'}</span></div></div>) : <p className="py-8 text-center text-sm text-slate-500">Nenhum faltante nesta doca.</p>}</div> : <p className="py-10 text-center text-sm text-slate-500">Clique em uma das 20 docas para visualizar os IDs faltantes sem sair do mapa.</p>}</aside></div></section>
    <div className="grid gap-3 sm:grid-cols-3">{[['A mais', counts.amais, 'border-red-300 text-[#b3261e]'], ['Faltantes', counts.faltantes, 'border-amber-300 text-[#6d4c00]'], ['Localizados', counts.localizados, 'border-emerald-300 text-emerald-700']].map(([label, count, style]) => <div key={String(label)} className={`rounded-xl border-2 bg-white p-4 shadow-sm ${style}`}><p className="text-xs font-bold text-slate-600">{label}</p><p className="mt-1 text-2xl font-black">{count}</p></div>)}</div>
    <section className="overflow-hidden rounded-xl border border-[#b7d9c2] bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-[#b7d9c2] bg-[#e2f3e7] p-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-2">{(['todos', 'A mais', 'Faltante'] as const).map(option => <button key={option} onClick={() => setFilter(option)} className={`rounded-md border px-3 py-2 text-xs font-bold ${filter === option ? 'border-[#2f6d4f] bg-[#cdebd6] text-[#174b33]' : 'border-transparent bg-white text-slate-600'}`}>{option === 'todos' ? 'Todos os erros' : option}</button>)}<span className="px-2 py-2 text-xs font-bold text-slate-500">{selectedDoca ? `Doca ${selectedDoca}` : 'Todas as docas'}</span></div><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar ID, rota ou placa" className="h-9 rounded-md border border-[#a8c8b0] bg-white pl-9 pr-3 text-xs outline-none focus:border-[#2f6d4f]"/></label></div>
      <div className="app-scroll-x"><table className="w-full min-w-[1050px] border-collapse text-center text-xs"><thead className="bg-[#f0f0f0] text-slate-950"><tr>{['ID', 'Origem', 'Placa', 'Rota Otimizada', 'Doca', 'Onda', 'Estado', 'Localizado', 'Indicador', 'Total'].map(head => <th key={head} className="border-b-2 border-r border-[#8f9bad] px-3 py-3 font-black last:border-r-0">{head}</th>)}</tr></thead><tbody>{rows.slice(0, 1000).map(row => <tr key={`${row.origem}-${row.pacote}-${row.rotaInformada}`} className="hover:bg-[#f7fbf8]"><td className="border-b border-r border-[#cbd5e1] px-3 py-2 font-mono font-bold">{row.pacote}</td><td className="border-b border-r border-[#cbd5e1] px-3 py-2 font-bold capitalize text-blue-700">{row.origem}</td><td className="border-b border-r border-[#cbd5e1] px-3 py-2 font-mono">{row.placa || '—'}</td><td className="border-b border-r border-[#cbd5e1] px-3 py-2 font-semibold">{row.rotaOtimizada || 'Não localizada'}</td><td className="border-b border-r border-[#cbd5e1] px-3 py-2">{row.doca || '—'}</td><td className="border-b border-r border-[#cbd5e1] px-3 py-2">{row.onda || '—'}</td><td className={`border-b border-r border-[#cbd5e1] px-3 py-2 font-black ${color(row.classificacao)}`}>{row.classificacao}</td><td className="border-b border-r border-[#cbd5e1] px-3 py-1"><input type="checkbox" checked={Boolean(store.localizados?.[row.pacote])} onChange={() => toggleLocated(row.pacote)} className="h-4 w-4 cursor-pointer accent-[#2f6d4f]" aria-label={`Marcar ${row.pacote} como localizado`} /></td><td className="border-b border-r border-[#cbd5e1] px-3 py-2 text-slate-400">—</td><td className="border-b border-[#cbd5e1] px-3 py-2 text-slate-400">—</td></tr>)}{!rows.length && <tr><td colSpan={10} className="px-4 py-12 text-center text-slate-400">Carregue os CSVs de Aduana e Auditoria para visualizar os erros.</td></tr>}</tbody></table></div></section>
    <div className="flex flex-wrap items-center justify-between gap-2 text-[11px] text-slate-400"><span>{store.updatedAt ? `Última atualização: ${new Date(store.updatedAt).toLocaleString('pt-BR')}` : 'Nenhuma base carregada'}</span><button onClick={resetExpedicao} className="inline-flex items-center gap-1 font-bold text-red-600 hover:text-red-800"><Trash2 className="h-3.5 w-3.5"/>Zerar expedição</button></div>
    {report && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4"><div className="w-full max-w-2xl overflow-hidden rounded-2xl border-2 border-slate-950 bg-white shadow-2xl"><div className="bg-[#102a67] px-6 py-5 text-white"><p className="text-xs font-black uppercase tracking-widest text-blue-200">Resumo salvo com sucesso</p><h2 className="mt-1 text-2xl font-black">Reporte diário de Expedição</h2><p className="mt-1 text-xs text-blue-100">Encerrado em {new Date().toLocaleString('pt-BR')}</p></div><div className="p-6"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-xl border-2 border-red-300 bg-red-50 p-3"><b className="text-2xl text-red-700">{counts.amais}</b><br/><span className="text-xs font-bold">A mais</span></div><div className="rounded-xl border-2 border-amber-300 bg-amber-50 p-3"><b className="text-2xl text-amber-700">{counts.faltantes}</b><br/><span className="text-xs font-bold">Faltantes</span></div><div className="rounded-xl border-2 border-emerald-300 bg-emerald-50 p-3"><b className="text-2xl text-emerald-700">{counts.localizados}</b><br/><span className="text-xs font-bold">Recuperados</span></div><div className="rounded-xl border-2 border-blue-300 bg-blue-50 p-3"><b className="text-2xl text-blue-700">{recoveryRate}%</b><br/><span className="text-xs font-bold">Taxa de recuperação</span></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border-2 border-slate-200 p-4"><h3 className="text-sm font-black">Fechamento do dia</h3><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><dt>Total de erros</dt><dd className="font-black">{totalErrors}</dd></div><div className="flex justify-between"><dt>Recuperados/localizados</dt><dd className="font-black text-emerald-700">{counts.localizados}</dd></div><div className="flex justify-between"><dt>Pendentes</dt><dd className="font-black text-red-700">{pending}</dd></div><div className="flex justify-between"><dt>Novos no histórico</dt><dd className="font-black">{(store.historico || []).filter(item => item.tipo === 'novo').length}</dd></div></dl></div><div className="rounded-xl border-2 border-slate-200 p-4"><h3 className="text-sm font-black">Docas com maior volume</h3><div className="mt-3 space-y-2">{criticalDocks.map(dock => <div key={dock.doca} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span className="font-bold">Doca {dock.doca}</span><span><b>{dock.amais + dock.faltantes}</b> erros</span></div>)}</div></div></div><div className="mt-6 flex justify-end gap-2"><button onClick={() => window.print()} className="rounded-lg border-2 border-slate-300 px-4 py-2 text-sm font-bold">Imprimir reporte</button><button onClick={() => setReport(false)} className="rounded-lg bg-[#253b80] px-4 py-2 text-sm font-bold text-white">Concluir</button></div></div></div></div>}
  </div>;
}
