import React, { useEffect, useMemo, useRef, useState } from 'react';
import { PackageCheck, Search, Trash2, UploadCloud } from 'lucide-react';
import { getLocalValue, setLocalValue } from '../lib/localPersistence';
import { enrichExpedicao, getChanges, parseBaseDespacho, parseExpedicaoRows, type ExpedicaoStore, type FonteExpedicao } from '../lib/expedicao';

const STORAGE_KEY = 'expedicao-daily-v1';
const empty: ExpedicaoStore = { base: [], aduana: [], auditoria: [], localizados: {}, historico: [], encerramentos: [] };
const color = (state: string) => state === 'A mais' ? 'bg-[#f4c7c3] text-[#b3261e]' : state === 'Faltante' ? 'bg-[#fde9a9] text-[#6d4c00]' : 'bg-emerald-100 text-emerald-800';

export function ExpedicaoPanel() {
  const [store, setStore] = useState<ExpedicaoStore>(empty);
  const [ready, setReady] = useState(false);
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<'todos' | 'A mais' | 'Faltante'>('todos');
  const [selectedDoca, setSelectedDoca] = useState<string | null>(null);
  const [report, setReport] = useState(false);
  const baseInput = useRef<HTMLInputElement>(null);
  const aduanaInput = useRef<HTMLInputElement>(null);
  const auditInput = useRef<HTMLInputElement>(null);

  useEffect(() => { getLocalValue<ExpedicaoStore>(STORAGE_KEY).then(saved => { if (saved) setStore({ ...empty, ...saved, localizados: saved.localizados || {} }); setReady(true); }); }, []);
  const save = async (next: ExpedicaoStore) => { setStore(next); await setLocalValue(STORAGE_KEY, next); };
  const importFile = async (file: File, source: 'base' | FonteExpedicao) => {
    const text = await file.text();
    const next = { ...store, updatedAt: new Date().toISOString(), filenames: { ...store.filenames, [source]: file.name } };
    if (source === 'base') next.base = parseBaseDespacho(text); else {
      const parsed = parseExpedicaoRows(text, source);
      next.historico = [...(store.historico || []), ...getChanges(store[source], parsed, source)].slice(-10000);
      next[source] = parsed;
    }
    await save(next);
  };
  const toggleLocated = (pacote: string) => save({ ...store, localizados: { ...store.localizados, [pacote]: !store.localizados?.[pacote] } });
  const enriched = useMemo(() => enrichExpedicao(store), [store]);
  const rows = enriched.filter(row => (filter === 'todos' || row.classificacao === filter) && (!selectedDoca || row.doca === selectedDoca) && `${row.pacote} ${row.rotaOtimizada} ${row.placa} ${row.onda}`.toLowerCase().includes(query.trim().toLowerCase()));
  const counts = useMemo(() => ({ amais: enriched.filter(row => row.origem === 'auditoria' && row.classificacao === 'A mais').length, faltantes: enriched.filter(row => row.origem === 'auditoria' && row.classificacao === 'Faltante').length, localizados: Object.values(store.localizados || {}).filter(Boolean).length }), [enriched, store.localizados]);
  const heatmap = useMemo(() => Array.from({ length: 20 }, (_, index) => {
    const doca = String(index + 1);
    const records = enriched.filter(row => row.origem === 'auditoria' && row.doca === doca);
    return { doca, amais: records.filter(row => row.classificacao === 'A mais').length, faltantes: records.filter(row => row.classificacao === 'Faltante').length };
  }), [enriched]);
  const closeExpedicao = async () => { const closing = { id: `exp-${Date.now()}`, encerradoEm: new Date().toISOString(), ...counts, porDoca: heatmap }; await save({ ...store, encerramentos: [closing, ...(store.encerramentos || [])] }); setReport(true); };
  if (!ready) return <div className="py-16 text-center text-sm text-slate-500">Carregando Expedição…</div>;
  const upload = (label: string, ref: React.RefObject<HTMLInputElement | null>, primary = false) => <button type="button" onClick={() => ref.current?.click()} className={`inline-flex items-center gap-2 rounded-lg px-3.5 py-2.5 text-xs font-black shadow-sm ${primary ? 'bg-[#253b80] text-white hover:bg-[#1f2464]' : 'border border-slate-200 bg-white text-slate-700 hover:bg-slate-50'}`}><UploadCloud className="h-4 w-4" />{label}</button>;
  return <div className="space-y-5">
    <input ref={baseInput} className="hidden" type="file" accept=".csv,text/csv" onChange={e => e.target.files?.[0] && importFile(e.target.files[0], 'base')} />
    <input ref={aduanaInput} className="hidden" type="file" accept=".csv,text/csv" onChange={e => e.target.files?.[0] && importFile(e.target.files[0], 'aduana')} />
    <input ref={auditInput} className="hidden" type="file" accept=".csv,text/csv" onChange={e => e.target.files?.[0] && importFile(e.target.files[0], 'auditoria')} />
    <section className="rounded-2xl border border-blue-100 bg-gradient-to-r from-white via-blue-50 to-white p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><div className="flex items-center gap-2 text-blue-700"><PackageCheck className="h-5 w-5" /><span className="text-xs font-bold uppercase tracking-wider">Expedição — Pacotes AMIS</span></div><h1 className="mt-2 text-3xl font-black tracking-tight text-[#102a67]">Concentração por doca</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">Contagem exclusiva dos erros A mais e Faltante do CSV de Auditoria.</p></div><div className="flex flex-wrap gap-2">{upload(store.base.length ? 'Atualizar Base Despacho' : '1. Carregar Base Despacho', baseInput, true)}{upload('Carregar Aduana', aduanaInput)}{upload('Carregar Auditoria', auditInput)}<button onClick={closeExpedicao} className="rounded-lg bg-[#ffd52f] px-3.5 py-2.5 text-xs font-black text-slate-950">Encerrar expedição</button></div></div></section>
    <section className="rounded-2xl border border-blue-100 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-black text-[#102a67]">Docas — 20 docas</h2><p className="text-xs text-slate-500">Clique em uma doca para abrir os IDs encontrados nela.</p></div>{selectedDoca && <button onClick={() => setSelectedDoca(null)} className="rounded-lg border px-3 py-2 text-xs font-bold">Ver todas</button>}</div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-5">{heatmap.map(item => { const total = item.amais + item.faltantes; const tone = total === 0 ? 'border-slate-200 bg-slate-50 text-slate-500' : total < 4 ? 'border-yellow-200 bg-yellow-50 text-amber-800' : total < 9 ? 'border-blue-200 bg-blue-50 text-blue-800' : 'border-red-200 bg-red-50 text-red-700'; return <button key={item.doca} onClick={() => setSelectedDoca(item.doca)} className={`rounded-xl border-l-[6px] p-4 text-left transition hover:-translate-y-0.5 hover:shadow-md ${tone} ${selectedDoca === item.doca ? 'ring-2 ring-[#2563eb]' : ''}`}><div className="text-sm font-black">DOCA {item.doca}</div><div className="mt-4 grid grid-cols-2 gap-2 border-t border-current/10 pt-3 text-xs"><span>A MAIS<b className="mt-1 block text-2xl">{item.amais}</b></span><span>FALTANTES<b className="mt-1 block text-2xl">{item.faltantes}</b></span></div></button>; })}</div></section>
    <div className="grid gap-3 sm:grid-cols-3">{[['A mais', counts.amais, 'text-[#b3261e]'], ['Faltantes', counts.faltantes, 'text-[#6d4c00]'], ['Localizados', counts.localizados, 'text-emerald-700']].map(([label, count, style]) => <div key={String(label)} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold text-slate-500">{label}</p><p className={`mt-1 text-2xl font-black ${style}`}>{count}</p></div>)}</div>
    <section className="overflow-hidden rounded-xl border border-[#b7d9c2] bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-[#b7d9c2] bg-[#e2f3e7] p-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-2">{(['todos', 'A mais', 'Faltante'] as const).map(option => <button key={option} onClick={() => setFilter(option)} className={`rounded-md border px-3 py-2 text-xs font-bold ${filter === option ? 'border-[#2f6d4f] bg-[#cdebd6] text-[#174b33]' : 'border-transparent bg-white text-slate-600'}`}>{option === 'todos' ? 'Todos os erros' : option}</button>)}<span className="px-2 py-2 text-xs font-bold text-slate-500">{selectedDoca ? `Doca ${selectedDoca}` : 'Todas as docas'}</span></div><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar ID, rota ou placa" className="h-9 rounded-md border border-[#a8c8b0] bg-white pl-9 pr-3 text-xs outline-none focus:border-[#2f6d4f]"/></label></div>
      <div className="app-scroll-x"><table className="w-full min-w-[990px] border-collapse text-center text-xs"><thead className="bg-[#f0f0f0] text-slate-950"><tr>{['ID', 'Placa', 'Rota Otimizada', 'Doca', 'Onda', 'Estado', 'Localizado', 'Indicador', 'Total'].map(head => <th key={head} className="border-b-2 border-r border-[#a5a5a5] px-3 py-3 font-black last:border-r-0">{head}</th>)}</tr></thead><tbody>{rows.slice(0, 1000).map(row => <tr key={`${row.origem}-${row.pacote}`} className="hover:bg-[#f7fbf8]"><td className="border-b border-r border-[#ddd] px-3 py-2 font-mono font-bold">{row.pacote}</td><td className="border-b border-r border-[#ddd] px-3 py-2 font-mono">{row.placa || '—'}</td><td className="border-b border-r border-[#ddd] px-3 py-2 font-semibold">{row.rotaOtimizada || 'Não localizada'}</td><td className="border-b border-r border-[#ddd] px-3 py-2">{row.doca || '—'}</td><td className="border-b border-r border-[#ddd] px-3 py-2">{row.onda || '—'}</td><td className={`border-b border-r border-[#ddd] px-3 py-2 font-black ${color(row.classificacao)}`}>{row.classificacao}</td><td className="border-b border-r border-[#ddd] px-3 py-1"><input type="checkbox" checked={Boolean(store.localizados?.[row.pacote])} onChange={() => toggleLocated(row.pacote)} className="h-4 w-4 cursor-pointer accent-[#2f6d4f]" aria-label={`Marcar ${row.pacote} como localizado`} /></td><td className="border-b border-r border-[#ddd] px-3 py-2 text-slate-400">—</td><td className="border-b border-[#ddd] px-3 py-2 text-slate-400">—</td></tr>)}{!rows.length && <tr><td colSpan={9} className="px-4 py-12 text-center text-slate-400">Carregue o CSV de {tab === 'aduana' ? 'Aduana' : 'Auditoria'} para iniciar.</td></tr>}</tbody></table></div></section>
    <div className="flex flex-wrap items-center justify-between gap-2 text-[11px] text-slate-400"><span>{store.updatedAt ? `Última atualização: ${new Date(store.updatedAt).toLocaleString('pt-BR')}` : 'Nenhuma base carregada'}</span><button onClick={() => { if (window.confirm('Apagar os dados salvos de Expedição neste navegador?')) save(empty); }} className="inline-flex items-center gap-1 hover:text-rose-600"><Trash2 className="h-3.5 w-3.5"/>Limpar Expedição</button></div>
    {report && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-2xl font-black">Reporte de Expedição</h2><p className="mt-1 text-sm text-slate-500">Encerrado em {new Date().toLocaleString('pt-BR')}</p><div className="mt-5 grid grid-cols-3 gap-3"><div className="rounded-lg bg-red-50 p-3"><b>{counts.amais}</b><br/><span className="text-xs">A mais</span></div><div className="rounded-lg bg-amber-50 p-3"><b>{counts.faltantes}</b><br/><span className="text-xs">Faltantes</span></div><div className="rounded-lg bg-emerald-50 p-3"><b>{counts.localizados}</b><br/><span className="text-xs">Localizados</span></div></div><p className="mt-5 text-sm">Novos registros nesta base: <b>{(store.historico || []).filter(item => item.tipo === 'novo').length}</b></p><div className="mt-6 flex justify-end gap-2"><button onClick={() => window.print()} className="rounded-lg border px-4 py-2 text-sm font-bold">Imprimir</button><button onClick={() => setReport(false)} className="rounded-lg bg-[#253b80] px-4 py-2 text-sm font-bold text-white">Concluir</button></div></div></div>}
  </div>;
}
